Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit
Public changer_id As Integer
Public comment As String
Public data_set_id As Long
Public executed_sql As String
Public field_name As String
Public new_value_var As Variant
Public new_value_number As Variant
Public record_id As Long
 